### PR TITLE
Fix label for attribute

### LINKED ISSUE #87: <label for='id'> should be replaced
Currently, if you have a `<label>` element, the `for` attribute expect an id. Since ids are renamed, so should be the `for` attribute.

I'm trying to correct this and submit a PR.

### PR DESCRIPTION
**Pull request by X-Ryl669**
Fix #87.
This fixes the missing renaming for `label for` attribute since this also expect an id (usually from an `input`)

### CODE REVIEW

File: lib/replace/html.js [hunk 1]
```diff
@@ -80,6 +80,11 @@ const replaceHtml = (code, opts = {}) => {
             selectorType = '#';
           }
 
+          if (node.tagName === 'label' && attr.name === 'for') {
```
Comment (JPeer264) [inline lib/replace/html.js]: Could have placed this as `||` in the if before. But ok for me :)

**Comment by JPeer264** [comment]
@X-Ryl669 seems like one test case is failing

**Comment by X-Ryl669** [comment]
I don't know why the test failed (maybe you've tested against a different master than mine?). I've rebased on the current master and all tests are good for me.

Unless stated otherwise, I'll rebase on this one for the next PR.
